version: "3.9"

services:
  db_cnab_parser:
    container_name: db_cnab_parser
    image: postgres
    env_file: .env
    ports:
      - 5436:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 7s
      timeout: 12s
      retries: 5

  migrations:
    build: .
    command: python manage.py migrate
    depends_on:
      db_cnab_parser:
        condition: service_healthy

  web:
    build: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      db_cnab_parser:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - .:/app/cnab_parser/
